name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./RoomAdvisor
          dockerfile: ./RoomAdvisor/Dockerfile
          push: true
          tags: leonburghardtdev/roomadvisor:latest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}

      - name: List Local Docker Images
        run: docker images

      - name: Pull Docker Image
        run: docker pull leonburghardtdev/roomadvisor:latest

      # Step 6: Inspect the Docker Image
      - name: Docker Image Inspect
        run: docker image inspect leonburghardtdev/roomadvisor:latest
